//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHD.SM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 10")]
        public global::System.Drawing.Point Frm_Main_Location {
            get {
                return ((global::System.Drawing.Point)(this["Frm_Main_Location"]));
            }
            set {
                this["Frm_Main_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 700")]
        public global::System.Drawing.Size Frm_Main_Size {
            get {
                return ((global::System.Drawing.Size)(this["Frm_Main_Size"]));
            }
            set {
                this["Frm_Main_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AHD.SM.LayoutPresent CurrentLayout {
            get {
                return ((global::AHD.SM.LayoutPresent)(this["CurrentLayout"]));
            }
            set {
                this["CurrentLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNewProjectWizard {
            get {
                return ((bool)(this["ShowNewProjectWizard"]));
            }
            set {
                this["ShowNewProjectWizard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int NewSubtitleDuration {
            get {
                return ((int)(this["NewSubtitleDuration"]));
            }
            set {
                this["NewSubtitleDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tahoma, 15.75pt")]
        public global::System.Drawing.Font NewSubtitleFont {
            get {
                return ((global::System.Drawing.Font)(this["NewSubtitleFont"]));
            }
            set {
                this["NewSubtitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color NewSubtitleColor {
            get {
                return ((global::System.Drawing.Color)(this["NewSubtitleColor"]));
            }
            set {
                this["NewSubtitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MediaSeekOnSelect {
            get {
                return ((bool)(this["MediaSeekOnSelect"]));
            }
            set {
                this["MediaSeekOnSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditMoreThanOneSubtitleUsingEditorWindow {
            get {
                return ((bool)(this["EditMoreThanOneSubtitleUsingEditorWindow"]));
            }
            set {
                this["EditMoreThanOneSubtitleUsingEditorWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProject {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProject"]));
            }
            set {
                this["RecentProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double AdvanceTime {
            get {
                return ((double)(this["AdvanceTime"]));
            }
            set {
                this["AdvanceTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int ShiftTime {
            get {
                return ((int)(this["ShiftTime"]));
            }
            set {
                this["ShiftTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFindItems {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFindItems"]));
            }
            set {
                this["RecentFindItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportDeepSearch {
            get {
                return ((bool)(this["ImportDeepSearch"]));
            }
            set {
                this["ImportDeepSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowQuickStart {
            get {
                return ((bool)(this["ShowQuickStart"]));
            }
            set {
                this["ShowQuickStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTipOfDay {
            get {
                return ((bool)(this["ShowTipOfDay"]));
            }
            set {
                this["ShowTipOfDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TipOfDayIndex {
            get {
                return ((int)(this["TipOfDayIndex"]));
            }
            set {
                this["TipOfDayIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AHD.SM.BooleansCollection EnabledFormats {
            get {
                return ((global::AHD.SM.BooleansCollection)(this["EnabledFormats"]));
            }
            set {
                this["EnabledFormats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCheckForErrors {
            get {
                return ((bool)(this["AutoCheckForErrors"]));
            }
            set {
                this["AutoCheckForErrors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSelectFirstTrack {
            get {
                return ((bool)(this["AutoSelectFirstTrack"]));
            }
            set {
                this["AutoSelectFirstTrack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskWhenChangingRTL {
            get {
                return ((bool)(this["AskWhenChangingRTL"]));
            }
            set {
                this["AskWhenChangingRTL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NewSubtitlesTrackTemplate {
            get {
                return ((bool)(this["NewSubtitlesTrackTemplate"]));
            }
            set {
                this["NewSubtitlesTrackTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditSubtitleAfterAddUsingQuickMode {
            get {
                return ((bool)(this["EditSubtitleAfterAddUsingQuickMode"]));
            }
            set {
                this["EditSubtitleAfterAddUsingQuickMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PauseAfterAddUsingQuickMode {
            get {
                return ((bool)(this["PauseAfterAddUsingQuickMode"]));
            }
            set {
                this["PauseAfterAddUsingQuickMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteFormat {
            get {
                return ((string)(this["FavoriteFormat"]));
            }
            set {
                this["FavoriteFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English (United States)")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SubtitleTextEditorBackColor {
            get {
                return ((global::System.Drawing.Color)(this["SubtitleTextEditorBackColor"]));
            }
            set {
                this["SubtitleTextEditorBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SubtitleTextEditorShowStatusStrip {
            get {
                return ((bool)(this["SubtitleTextEditorShowStatusStrip"]));
            }
            set {
                this["SubtitleTextEditorShowStatusStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int PlayerTimer {
            get {
                return ((int)(this["PlayerTimer"]));
            }
            set {
                this["PlayerTimer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MegnaticAccuracy {
            get {
                return ((int)(this["MegnaticAccuracy"]));
            }
            set {
                this["MegnaticAccuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int SmartToolAccuracy {
            get {
                return ((int)(this["SmartToolAccuracy"]));
            }
            set {
                this["SmartToolAccuracy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnMeWhenID3Detected {
            get {
                return ((bool)(this["WarnMeWhenID3Detected"]));
            }
            set {
                this["WarnMeWhenID3Detected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarnMeWhenMKVDetected {
            get {
                return ((bool)(this["WarnMeWhenMKVDetected"]));
            }
            set {
                this["WarnMeWhenMKVDetected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeekMediaToNewSubtitlesStartTimeAfterAdd {
            get {
                return ((bool)(this["SeekMediaToNewSubtitlesStartTimeAfterAdd"]));
            }
            set {
                this["SeekMediaToNewSubtitlesStartTimeAfterAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultID3V2Version {
            get {
                return ((int)(this["DefaultID3V2Version"]));
            }
            set {
                this["DefaultID3V2Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ID3V2_UseUnsynchronisation {
            get {
                return ((bool)(this["ID3V2_UseUnsynchronisation"]));
            }
            set {
                this["ID3V2_UseUnsynchronisation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ID3V2_KeepPadding {
            get {
                return ((bool)(this["ID3V2_KeepPadding"]));
            }
            set {
                this["ID3V2_KeepPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ID3V2_DropExtendedHeader {
            get {
                return ((bool)(this["ID3V2_DropExtendedHeader"]));
            }
            set {
                this["ID3V2_DropExtendedHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ID3V2_WriteFooter {
            get {
                return ((bool)(this["ID3V2_WriteFooter"]));
            }
            set {
                this["ID3V2_WriteFooter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCreateSubtitlesTrackAfterCreatingNewProject {
            get {
                return ((bool)(this["AutoCreateSubtitlesTrackAfterCreatingNewProject"]));
            }
            set {
                this["AutoCreateSubtitlesTrackAfterCreatingNewProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowErrorsInEditControl {
            get {
                return ((bool)(this["AllowErrorsInEditControl"]));
            }
            set {
                this["AllowErrorsInEditControl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskToExportBeforeUpload {
            get {
                return ((bool)(this["AskToExportBeforeUpload"]));
            }
            set {
                this["AskToExportBeforeUpload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveEnabled {
            get {
                return ((bool)(this["AutoSaveEnabled"]));
            }
            set {
                this["AutoSaveEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int AutoSavePeriodMinutes {
            get {
                return ((int)(this["AutoSavePeriodMinutes"]));
            }
            set {
                this["AutoSavePeriodMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Space")]
        public string ShortcutAddSubtitle {
            get {
                return ((string)(this["ShortcutAddSubtitle"]));
            }
            set {
                this["ShortcutAddSubtitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F6")]
        public string ShortcutNextSubtitle {
            get {
                return ((string)(this["ShortcutNextSubtitle"]));
            }
            set {
                this["ShortcutNextSubtitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F5")]
        public string ShortcutPreviousSubtitle {
            get {
                return ((string)(this["ShortcutPreviousSubtitle"]));
            }
            set {
                this["ShortcutPreviousSubtitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F7")]
        public string ShortcutJumpIntoSelectedSubtitleTime {
            get {
                return ((string)(this["ShortcutJumpIntoSelectedSubtitleTime"]));
            }
            set {
                this["ShortcutJumpIntoSelectedSubtitleTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddNewSubtitleTextWhenAddNewSubtitle {
            get {
                return ((bool)(this["AddNewSubtitleTextWhenAddNewSubtitle"]));
            }
            set {
                this["AddNewSubtitleTextWhenAddNewSubtitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AskBeforeDeletingSubtitle {
            get {
                return ((bool)(this["AskBeforeDeletingSubtitle"]));
            }
            set {
                this["AskBeforeDeletingSubtitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ScrollTimelineToMediaOnMediaSlide {
            get {
                return ((bool)(this["ScrollTimelineToMediaOnMediaSlide"]));
            }
            set {
                this["ScrollTimelineToMediaOnMediaSlide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Right")]
        public string ShortcutFWD {
            get {
                return ((string)(this["ShortcutFWD"]));
            }
            set {
                this["ShortcutFWD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public string ShortcutREW {
            get {
                return ((string)(this["ShortcutREW"]));
            }
            set {
                this["ShortcutREW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CheckForUpdatesAutoamtically {
            get {
                return ((bool)(this["CheckForUpdatesAutoamtically"]));
            }
            set {
                this["CheckForUpdatesAutoamtically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int WaveFormQuality {
            get {
                return ((int)(this["WaveFormQuality"]));
            }
            set {
                this["WaveFormQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F10")]
        public string ShortcutStretchToNext {
            get {
                return ((string)(this["ShortcutStretchToNext"]));
            }
            set {
                this["ShortcutStretchToNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F9")]
        public string ShortcutStretchToPrevious {
            get {
                return ((string)(this["ShortcutStretchToPrevious"]));
            }
            set {
                this["ShortcutStretchToPrevious"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimelineAutoGenerateWaveform {
            get {
                return ((bool)(this["TimelineAutoGenerateWaveform"]));
            }
            set {
                this["TimelineAutoGenerateWaveform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MediaPlayerEnableSubtitlePreview {
            get {
                return ((bool)(this["MediaPlayerEnableSubtitlePreview"]));
            }
            set {
                this["MediaPlayerEnableSubtitlePreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MediaPlayerUseSubtitleFormatting {
            get {
                return ((bool)(this["MediaPlayerUseSubtitleFormatting"]));
            }
            set {
                this["MediaPlayerUseSubtitleFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 15.75pt, style=Bold")]
        public global::System.Drawing.Font MediaPlayerCustomFont {
            get {
                return ((global::System.Drawing.Font)(this["MediaPlayerCustomFont"]));
            }
            set {
                this["MediaPlayerCustomFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color MediaPlayerCustomColor {
            get {
                return ((global::System.Drawing.Color)(this["MediaPlayerCustomColor"]));
            }
            set {
                this["MediaPlayerCustomColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("player.wmp")]
        public string MediaPlayerCurrent {
            get {
                return ((string)(this["MediaPlayerCurrent"]));
            }
            set {
                this["MediaPlayerCurrent"] = value;
            }
        }
    }
}
