// This file is part of AHD Subtitles Maker
// A program that can make and edit subtitle.
// 
// Copyright © Alaa Ibrahim Hadid 2009 - 2021
//
// This library is free software; you can redistribute it and/or modify 
// it under the terms of the GNU Lesser General Public License as published 
// by the Free Software Foundation; either version 3 of the License, 
// or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful, but 
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE.See the GNU Lesser General Public 
// License for more details.
//
// You should have received a copy of the GNU Lesser General Public License 
// along with this library; if not, write to the Free Software Foundation, 
// Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
// 
// Author email: mailto:alaahadidfreeware@gmail.com
//
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHD.SM.Controls {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    public sealed partial class ControlsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ControlsSettings defaultInstance = ((ControlsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ControlsSettings())));
        
        public static ControlsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SubtitlesData_ViewIndex {
            get {
                return ((int)(this["SubtitlesData_ViewIndex"]));
            }
            set {
                this["SubtitlesData_ViewIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int SubtitlesData_startime {
            get {
                return ((int)(this["SubtitlesData_startime"]));
            }
            set {
                this["SubtitlesData_startime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int SubtitlesData_endime {
            get {
                return ((int)(this["SubtitlesData_endime"]));
            }
            set {
                this["SubtitlesData_endime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int SubtitlesData_duration {
            get {
                return ((int)(this["SubtitlesData_duration"]));
            }
            set {
                this["SubtitlesData_duration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int SubtitlesData_text {
            get {
                return ((int)(this["SubtitlesData_text"]));
            }
            set {
                this["SubtitlesData_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SubtitlesData_number {
            get {
                return ((int)(this["SubtitlesData_number"]));
            }
            set {
                this["SubtitlesData_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::AHD.SM.Controls.EncodingsCollection FavoriteEncodings {
            get {
                return ((global::AHD.SM.Controls.EncodingsCollection)(this["FavoriteEncodings"]));
            }
            set {
                this["FavoriteEncodings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Timeline_AutoScroll {
            get {
                return ((bool)(this["Timeline_AutoScroll"]));
            }
            set {
                this["Timeline_AutoScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int Timeline_zoomValue {
            get {
                return ((int)(this["Timeline_zoomValue"]));
            }
            set {
                this["Timeline_zoomValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Timeline_S {
            get {
                return ((bool)(this["Timeline_S"]));
            }
            set {
                this["Timeline_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Timeline_L {
            get {
                return ((bool)(this["Timeline_L"]));
            }
            set {
                this["Timeline_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Timeline_C {
            get {
                return ((bool)(this["Timeline_C"]));
            }
            set {
                this["Timeline_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Timeline_G {
            get {
                return ((bool)(this["Timeline_G"]));
            }
            set {
                this["Timeline_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Vertical_T {
            get {
                return ((bool)(this["Vertical_T"]));
            }
            set {
                this["Vertical_T"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Vertical_S {
            get {
                return ((bool)(this["Vertical_S"]));
            }
            set {
                this["Vertical_S"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Vertical_L {
            get {
                return ((bool)(this["Vertical_L"]));
            }
            set {
                this["Vertical_L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int Vertical_WW {
            get {
                return ((int)(this["Vertical_WW"]));
            }
            set {
                this["Vertical_WW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int Timeline_Spl1 {
            get {
                return ((int)(this["Timeline_Spl1"]));
            }
            set {
                this["Timeline_Spl1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("53")]
        public int Timeline_Spl2 {
            get {
                return ((int)(this["Timeline_Spl2"]));
            }
            set {
                this["Timeline_Spl2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("56")]
        public int Timeline_Spl3 {
            get {
                return ((int)(this["Timeline_Spl3"]));
            }
            set {
                this["Timeline_Spl3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SubtitlesData_IsTimeline {
            get {
                return ((bool)(this["SubtitlesData_IsTimeline"]));
            }
            set {
                this["SubtitlesData_IsTimeline"] = value;
            }
        }
    }
}
